# Generated by Django 5.2.6 on 2025-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaaS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='google_drive_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
