# Generated by Django 5.2.6 on 2025-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaaS', '0002_alter_document_google_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('EXCEL', 'Excel Spreadsheet'), ('GDOC', 'Google Document'), ('GSHEET', 'Google Spreadsheet'), ('GSLIDES', 'Google Presentation')], max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='google_drive_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('user', 'google_drive_id')},
        ),
    ]
